export const REG_CALLED = 'REG_CALLED';
export const REG_RETURNED = 'REG_RETURNED';
export const REG_ERROR = 'REG_ERROR';

export const LOGIN_CALLED = 'LOGIN_CALLED';
export const LOGIN_RETURNED = 'LOGIN_RETURNED';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CREATE_CLASS_CALLED = 'CREATE_CLASS_CALLED';
export const CREATE_CLASS_RETURNED = 'CREATE_CLASS_RETURNED';
export const CREATE_CLASS_ERROR = 'CREATE_CLASS_ERROR';


export const GET_CLASSES = 'GET_CLASSES';
export const GET_CALENDAR = 'GET_CALENDAR';
export const SCHEDULE_CLASS_RETURNED = 'SCHEDULE_CLASS_RETURNED'

export const GET_INSTRUCTORS = 'GET_INSTRUCTORS'
export const GET_CLASSES_TYPES = 'GET_CLASSES_TYPES'

export const NEW_CLASS_TYPE = 'NEW_CLASS_TYPE';

export const ATTEND_CLASS = 'ATTEND_CLASS';
export const ATTEND_CLASS_SUCCESS = 'ATTEND_CLASS_SUCCESS';

export const BUY_PASS = 'BUY_PASS';
export const BUY_PASS_SUCCESS = 'BUY_PASS_SUCCESS';

export const CLEAR_PASS = 'NEW_CLASS_TYPE';
export const CLEAR_PASS_SUCCESS = 'NEW_CLASS_TYPE_SUCCESS';
