export const REG_CALLED = 'REG_CALLED';
export const REG_RETURNED = 'REG_RETURNED';
export const REG_ERROR = 'REG_ERROR';

export const LOGIN_CALLED = 'LOGIN_CALLED';
export const LOGIN_RETURNED = 'LOGIN_RETURNED';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SCHEDULE_CLASS_RETURNED = 'SCHEDULE_CLASS_RETURNED'

export const GET_INSTRUCTORS = 'GET_INSTRUCTORS'
export const GET_CLASSES_TYPES = 'GET_CLASSES_TYPES'

export const NEW_CLASS_TYPE = 'NEW_CLASS_TYPE'