
export const CREATE_CLASS_CALLED = 'CREATE_CLASS_CALLED';
export const CREATE_CLASS_RETURNED = 'CREATE_CLASS_RETURNED';
export const CREATE_CLASS_ERROR = 'CREATE_CLASS_ERROR';


export const GET_CLASSES = 'GET_CLASSES';
export const GET_CALENDAR = 'GET_CALENDAR';
export const SCHEDULE_CLASS_RETURNED = 'SCHEDULE_CLASS_RETURNED'

export const GET_INSTRUCTORS = 'GET_INSTRUCTORS'
export const GET_CLASSES_TYPES = 'GET_CLASSES_TYPES'

export const NEW_CLASS_TYPE = 'NEW_CLASS_TYPE';

export const ATTEND_CLASS = 'ATTEND_CLASS';
export const ATTEND_CLASS_SUCCESS = 'ATTEND_CLASS_SUCCESS';

export const BUY_PASS = 'BUY_PASS';
export const BUY_PASS_SUCCESS = 'BUY_PASS_SUCCESS';

export const CLEAR_PASS = 'NEW_CLASS_TYPE';
export const CLEAR_PASS_SUCCESS = 'NEW_CLASS_TYPE_SUCCESS';

export const PROTECTED_REG_CALLED = 'PROTECTED_REG_CALLED';
export const PROTECTED_REG_RETURNED = 'PROTECTED_REG_RETURNED';
export const PROTECTED_REG_ERROR = 'PROTECTED_REG_ERROR';

export const PROTECTED_LOGIN_CALLED = 'PROTECTED_LOGIN_CALLED';
export const PROTECTED_LOGIN_RETURNED = 'PROTECTED_LOGIN_RETURNED';
export const PROTECTED_LOGIN_ERROR = 'PROTECTED_LOGIN_ERROR';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';
